#!/usr/bin/env node

'use strict';


var bookmaker, done, fs, generate, load, loader, sequence, whenjs;

bookmaker = require('./src/index');

fs = require('fs');

whenjs = require('when');

sequence = require('when/sequence');

var os = require('os');
var path = require('path');
var fs = require('fs');

var temppath = path.resolve(os.tmpDir(), 'bm' + require('crypto').randomBytes(4).toString('hex'));
var args = process.argv.splice(2);
var tempdir = fs.mkdirSync(temppath);
var rimraf = require('rimraf');
done = function() {
  console.log('Cleaning up.');
  rimraf(temppath, function(err) {
    if (err) {
      console.error(err);
    }
    console.log('Done');
  });
};

var target = args[1];

if (target[target.length - 1] !== '/') {
  target = target + '/';
}

console.log(target);


generate = function(book) {
  var tasks;
  tasks = [];
  tasks.push(book.assets.init());
  tasks.push(book.toHtmlAndJsonFiles(target));
  return whenjs.all(tasks);
};

load = function(book) {
  return generate(book).then(function() {done()});
};


loader = bookmaker.Book.fromEpub(args[0], temppath);

loader.then(function(book) {
  return load(book);
});
